//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_prueba_001.Data.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bd_estacionamientosEntities : DbContext
    {
        public bd_estacionamientosEntities()
            : base("name=bd_estacionamientosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<autos_cliente> autos_cliente { get; set; }
        public virtual DbSet<clientes> clientes { get; set; }
        public virtual DbSet<estado_plaza> estado_plaza { get; set; }
        public virtual DbSet<plaza_autos> plaza_autos { get; set; }
    }
}
